server:
  port: 80

spring:
#  datasource:
#    username: root
#    password: 123456
#    url: jdbc:mysql://localhost:3306/itstack?useUnicode=true&characterEncoding=utf8
#    driver-class-name: com.mysql.jdbc.Driver

  datasource:
    username: root
    password: QQ!!@qq112
    url: jdbc:mysql://mysql57.rdsmjqserkdxj4n.rds.bj.baidubce.com:3306/itstack?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml

# 微信公众号配置信息
# originalid：原始ID
# appid：个人AppID
# token：开通接口服务自定义设置
wx:
  config:
    originalid: gh_18c526311f7e
    appid: wx51d84c9cbbbb1a90
    token: bugstack
